# Generated by Django 3.2.7 on 2021-09-30 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('7fbf01c0-8057-4879-998b-550a1a9d0c85'), editable=False, unique=True),
        ),
    ]
