# Generated by Django 3.2.7 on 2021-09-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210918_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
