# Generated by Django 3.2.7 on 2021-09-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210918_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='text',
        ),
    ]
