# Generated by Django 3.2.7 on 2021-09-21 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210921_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('41cff841-112e-4a21-9e4b-9d3195666906'), editable=False, unique=True),
        ),
    ]
