# Generated by Django 3.2.7 on 2021-09-21 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_apitoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('1ab3c2a9-68f3-4ade-8591-5f6058644143'), editable=False, unique=True),
        ),
    ]
